octoprint_1:
  restart: always
  image: petergrace/octodocker
  volumes:
    - /root/octodocker/sd4:/home/octoprint
    - /root/octodocker/uploads:/home/octoprint/.octoprint/uploads
  devices:
    - "/dev/ttyACM0:/dev/ttyUSB0"
  environment:
    - OCTOPORT=25501
  ports:
    - "25501:25501"

octoprint_2:
  restart: always
  image: petergrace/octodocker
  volumes:
    - /root/octodocker/i3pro:/home/octoprint
    - /root/octodocker/uploads:/home/octoprint/.octoprint/uploads
  devices:
    - "/dev/ttyACM1:/dev/ttyUSB0"
  environment:
    - OCTOPORT=25502
  ports:
    - "25502:25502"

